"""Unit tests for PMDocumentGenerator — LLM-based PM generation.

Tests the PMDocumentGenerator class which uses an LLM to generate a rich
pm.md from full Q&A transcript plus PMSeed, with fallback to template-based
generation on failure.
"""

from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest

from mobius.bigbang.pm_document import (
    PMDocumentGenerator,
)
from mobius.bigbang.pm_seed import PMSeed, UserStory
from mobius.core.errors import ProviderError
from mobius.core.types import Result
from mobius.providers.base import (
    CompletionResponse,
    UsageInfo,
)

# ──────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────

_SAMPLE_PM_MD = """\
# Task Manager

*Generated by Mobius PM Generator*

## Goal

Build a task management tool for small teams.

## User Stories

1. **As a** team lead, **I want to** assign tasks, **so that** work is distributed.

## Constraints

- Must launch within 3 months

## Success Criteria

1. 80% user adoption in first quarter

---
*PM ID: pm_seed_test123*
*Interview ID: int_abc*
"""


def _make_seed(**overrides) -> PMSeed:
    """Create a PMSeed with sensible defaults for testing."""
    defaults = {
        "pm_id": "pm_seed_test123",
        "product_name": "Task Manager",
        "goal": "Build a task management tool for small teams.",
        "user_stories": (
            UserStory(
                persona="team lead",
                action="assign tasks",
                benefit="work is distributed",
            ),
        ),
        "constraints": ("Must launch within 3 months",),
        "success_criteria": ("80% user adoption in first quarter",),
        "deferred_items": ("API rate limiting",),
        "decide_later_items": ("Which database to use?",),
        "assumptions": ("Team has access to cloud infra",),
        "interview_id": "int_abc",
    }
    defaults.update(overrides)
    return PMSeed(**defaults)


def _make_adapter(content: str = _SAMPLE_PM_MD) -> MagicMock:
    """Create a mock LLM adapter returning the given content."""
    adapter = MagicMock()
    adapter.complete = AsyncMock(
        return_value=Result.ok(
            CompletionResponse(
                content=content,
                model="claude-opus-4-6",
                usage=UsageInfo(
                    prompt_tokens=500,
                    completion_tokens=300,
                    total_tokens=800,
                ),
            )
        )
    )
    return adapter


def _make_failing_adapter() -> MagicMock:
    """Create a mock adapter that returns an error."""
    adapter = MagicMock()
    adapter.complete = AsyncMock(return_value=Result.err(ProviderError("LLM service unavailable")))
    return adapter


def _sample_qa_pairs() -> list[tuple[str, str]]:
    """Return sample Q&A pairs for testing."""
    return [
        ("What problem does this solve?", "Our team needs better task tracking."),
        ("Who are the primary users?", "Team leads and developers."),
        ("What are your success metrics?", "80% adoption in Q1."),
    ]


# ──────────────────────────────────────────────────────────────────
# PMDocumentGenerator.generate() tests
# ──────────────────────────────────────────────────────────────────


class TestPMDocumentGeneratorGenerate:
    """Tests for PMDocumentGenerator.generate()."""

    @pytest.mark.asyncio
    async def test_generate_with_qa_pairs_returns_llm_content(self):
        """LLM-generated content is returned when call succeeds."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        result = await generator.generate(seed, qa_pairs=_sample_qa_pairs())

        assert result.is_ok
        assert "Task Manager" in result.value
        # Verify LLM was called
        adapter.complete.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_generate_without_qa_pairs(self):
        """Generate works with seed only (no Q&A transcript)."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        result = await generator.generate(seed)

        assert result.is_ok
        adapter.complete.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_generate_extracts_qa_from_interview_state(self):
        """Q&A pairs are extracted from InterviewState when provided."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        # Mock InterviewState with rounds
        mock_state = MagicMock()
        mock_round1 = MagicMock()
        mock_round1.question = "What problem?"
        mock_round1.user_response = "Task tracking."
        mock_round2 = MagicMock()
        mock_round2.question = "Who uses it?"
        mock_round2.user_response = "Developers."
        mock_state.rounds = [mock_round1, mock_round2]

        result = await generator.generate(seed, interview_state=mock_state)

        assert result.is_ok
        # Verify the prompt includes Q&A from state
        call_args = adapter.complete.call_args
        messages = call_args[0][0]
        user_msg = messages[1].content
        assert "What problem?" in user_msg
        assert "Task tracking." in user_msg

    @pytest.mark.asyncio
    async def test_generate_qa_pairs_take_precedence_over_state(self):
        """Explicit qa_pairs take precedence over interview_state."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        mock_state = MagicMock()
        mock_round = MagicMock()
        mock_round.question = "State question"
        mock_round.user_response = "State answer"
        mock_state.rounds = [mock_round]

        explicit_pairs = [("Explicit Q", "Explicit A")]

        result = await generator.generate(
            seed,
            qa_pairs=explicit_pairs,
            interview_state=mock_state,
        )

        assert result.is_ok
        call_args = adapter.complete.call_args
        user_msg = call_args[0][0][1].content
        assert "Explicit Q" in user_msg
        assert "State question" not in user_msg

    @pytest.mark.asyncio
    async def test_generate_falls_back_to_template_on_llm_error(self):
        """Falls back to template-based generation when LLM fails."""
        adapter = _make_failing_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        result = await generator.generate(seed, qa_pairs=_sample_qa_pairs())

        assert result.is_ok
        # Should contain template-generated content
        content = result.value
        assert "# Task Manager" in content
        assert "## Goal" in content

    @pytest.mark.asyncio
    async def test_generate_falls_back_on_too_short_response(self):
        """Falls back to template when LLM returns very short content."""
        adapter = _make_adapter(content="OK")  # Too short
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        result = await generator.generate(seed)

        assert result.is_ok
        # Should contain template content, not the short "OK"
        assert "## Goal" in result.value

    @pytest.mark.asyncio
    async def test_generate_falls_back_on_empty_response(self):
        """Falls back to template when LLM returns empty content."""
        adapter = _make_adapter(content="")
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        result = await generator.generate(seed)

        assert result.is_ok
        assert "# Task Manager" in result.value


# ──────────────────────────────────────────────────────────────────
# PMDocumentGenerator prompt building tests
# ──────────────────────────────────────────────────────────────────


class TestPMDocumentGeneratorPrompt:
    """Tests for the prompt building logic."""

    def test_prompt_includes_seed_fields(self):
        """Prompt includes all relevant PMSeed fields."""
        seed = _make_seed()
        prompt = PMDocumentGenerator._build_generation_prompt(seed)

        assert "Task Manager" in prompt
        assert "Build a task management" in prompt
        assert "team lead" in prompt
        assert "assign tasks" in prompt
        assert "Must launch within 3 months" in prompt
        assert "80% user adoption" in prompt
        assert "API rate limiting" in prompt
        assert "Which database to use?" in prompt
        assert "Team has access to cloud infra" in prompt

    def test_prompt_includes_qa_pairs(self):
        """Prompt includes the full Q&A transcript."""
        seed = _make_seed()
        qa = _sample_qa_pairs()
        prompt = PMDocumentGenerator._build_generation_prompt(seed, qa)

        assert "## Full Interview Transcript" in prompt
        assert "**Q1:**" in prompt
        assert "**A1:**" in prompt
        assert "What problem does this solve?" in prompt
        assert "Our team needs better task tracking." in prompt

    def test_prompt_omits_transcript_section_when_no_qa(self):
        """Transcript section is omitted when no Q&A pairs provided."""
        seed = _make_seed()
        prompt = PMDocumentGenerator._build_generation_prompt(seed)

        assert "## Full Interview Transcript" not in prompt

    def test_prompt_includes_brownfield_repos(self):
        """Prompt includes brownfield repo information."""
        seed = _make_seed(
            brownfield_repos=({"path": "/code/myapp", "name": "MyApp", "desc": "Main app"},),
        )
        prompt = PMDocumentGenerator._build_generation_prompt(seed)

        assert "MyApp" in prompt
        assert "/code/myapp" in prompt
        assert "Main app" in prompt

    def test_prompt_excludes_codebase_context(self):
        """Prompt excludes codebase analysis (technical detail not for PMs)."""
        seed = _make_seed(codebase_context="Uses FastAPI with PostgreSQL backend.")
        prompt = PMDocumentGenerator._build_generation_prompt(seed)

        assert "Codebase Analysis" not in prompt
        assert "Uses FastAPI with PostgreSQL backend." not in prompt

    def test_prompt_handles_empty_seed(self):
        """Prompt handles a minimal seed with empty fields gracefully."""
        seed = PMSeed()
        prompt = PMDocumentGenerator._build_generation_prompt(seed)

        assert "## Extracted Requirements" in prompt
        assert "Not specified" in prompt  # goal fallback
        assert "Unnamed" in prompt  # product_name fallback

    def test_prompt_truncates_long_codebase_context(self):
        """Codebase context is truncated to prevent token overflow."""
        long_context = "x" * 5000
        seed = _make_seed(codebase_context=long_context)
        prompt = PMDocumentGenerator._build_generation_prompt(seed)

        # Should be truncated to 3000 chars
        assert len(prompt) < len(long_context) + 2000

    def test_prompt_generation_instruction_at_end(self):
        """Prompt ends with the generation instruction."""
        seed = _make_seed()
        prompt = PMDocumentGenerator._build_generation_prompt(seed)

        assert prompt.strip().endswith(
            "Generate a polished PM document from the above requirements and interview transcript."
        )


# ──────────────────────────────────────────────────────────────────
# PMDocumentGenerator.save() tests
# ──────────────────────────────────────────────────────────────────


class TestPMDocumentGeneratorSave:
    """Tests for PMDocumentGenerator.save()."""

    def test_save_writes_to_default_dir(self, tmp_path: Path, monkeypatch):
        """Save writes pm.md to .mobius/ by default."""
        monkeypatch.chdir(tmp_path)
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        path = generator.save("# My PM", seed)

        assert path.exists()
        assert path.name == "pm.md"
        assert path.parent.name == ".mobius"
        assert path.read_text() == "# My PM"

    def test_save_writes_to_custom_dir(self, tmp_path: Path):
        """Save writes pm.md to custom output directory."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        custom_dir = tmp_path / "custom"
        path = generator.save("# Custom PM", seed, output_dir=custom_dir)

        assert path.exists()
        assert path == custom_dir / "pm.md"
        assert path.read_text() == "# Custom PM"

    def test_save_creates_directories(self, tmp_path: Path):
        """Save creates parent directories if they don't exist."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        nested_dir = tmp_path / "a" / "b" / "c"
        path = generator.save("# Nested", seed, output_dir=nested_dir)

        assert path.exists()
        assert path.read_text() == "# Nested"


# ──────────────────────────────────────────────────────────────────
# PMDocumentGenerator.generate_and_save() tests
# ──────────────────────────────────────────────────────────────────


class TestPMDocumentGeneratorGenerateAndSave:
    """Tests for the convenience generate_and_save method."""

    @pytest.mark.asyncio
    async def test_generate_and_save_success(self, tmp_path: Path):
        """generate_and_save produces and persists pm.md."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        result = await generator.generate_and_save(
            seed,
            qa_pairs=_sample_qa_pairs(),
            output_dir=tmp_path,
        )

        assert result.is_ok
        path = result.value
        assert path.exists()
        assert path.name == "pm.md"
        content = path.read_text()
        assert "Task Manager" in content

    @pytest.mark.asyncio
    async def test_generate_and_save_with_interview_state(self, tmp_path: Path):
        """generate_and_save extracts Q&A from InterviewState."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        mock_state = MagicMock()
        mock_round = MagicMock()
        mock_round.question = "What problem?"
        mock_round.user_response = "Tracking."
        mock_state.rounds = [mock_round]

        result = await generator.generate_and_save(
            seed,
            interview_state=mock_state,
            output_dir=tmp_path,
        )

        assert result.is_ok
        assert result.value.exists()

    @pytest.mark.asyncio
    async def test_generate_and_save_fallback_on_error(self, tmp_path: Path):
        """generate_and_save falls back to template on LLM failure and still saves."""
        adapter = _make_failing_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        result = await generator.generate_and_save(
            seed,
            qa_pairs=_sample_qa_pairs(),
            output_dir=tmp_path,
        )

        # Should still succeed via fallback
        assert result.is_ok
        content = result.value.read_text()
        assert "## Goal" in content


# ──────────────────────────────────────────────────────────────────
# LLM message structure tests
# ──────────────────────────────────────────────────────────────────


class TestPMDocumentGeneratorMessages:
    """Tests for the LLM message structure sent by generate()."""

    @pytest.mark.asyncio
    async def test_system_message_contains_pm_instructions(self):
        """System prompt instructs LLM to write a PM."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed()

        await generator.generate(seed, qa_pairs=_sample_qa_pairs())

        call_args = adapter.complete.call_args
        messages = call_args[0][0]

        assert len(messages) == 2
        assert messages[0].role.value == "system"
        assert "Product Requirements Document" in messages[0].content
        assert messages[1].role.value == "user"

    @pytest.mark.asyncio
    async def test_completion_config_parameters(self):
        """Completion config uses appropriate parameters for document generation."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter, model="test-model")
        seed = _make_seed()

        await generator.generate(seed)

        call_args = adapter.complete.call_args
        config = call_args[0][1]

        assert config.model == "test-model"
        assert config.temperature == 0.3
        assert config.max_tokens == 8192

    @pytest.mark.asyncio
    async def test_user_message_includes_all_seed_sections(self):
        """User message includes all populated seed sections."""
        adapter = _make_adapter()
        generator = PMDocumentGenerator(llm_adapter=adapter)
        seed = _make_seed(
            brownfield_repos=({"path": "/repo", "name": "Repo", "desc": "Test"},),
            codebase_context="Python FastAPI project.",
        )
        qa = [("Q1", "A1")]

        await generator.generate(seed, qa_pairs=qa)

        user_msg = adapter.complete.call_args[0][0][1].content

        assert "Extracted Requirements" in user_msg
        assert "Task Manager" in user_msg
        assert "Full Interview Transcript" in user_msg
        assert "Q1" in user_msg
        assert "Repo" in user_msg
        # Codebase analysis is excluded from PM prompts
        assert "Python FastAPI project." not in user_msg
